service: contact-request
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: eu-west-2
  stage: ${env:STAGE}

environment:
  SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}

package:
  exclude:
    - ./**
  include:
    - ./bin/**


functions:
  contactHandler:
    handler: bin/main
    events:
      - http:
          path: contact
          method: post
          cors: true
